### ISSUE TITLE
resolve_duplicates function issue

### ISSUE THREAD

**Issue by BrElio** [searchwp/searchwp-term-priority#1]
The extension doesn't return results unless the resolve_duplicates functions is removed.
The problem seems to be at line 348-349 in that function but needs to be tested further.

**Comment by jchristopher** [comment]
After some back-and-forth with @BrElio it was discovered that the issue occurs only when a taxonomy is added to only one post type. The function likely assumes that the taxonomy has been added to all post types but that is not the case. Working on a fix now.
